#!/system/bin/sh

# init.d support

echo "Starting init.d..."

mount -o remount,rw /system

chmod -R 755 /system/etc/init.d/*

for FILE in /system/etc/init.d/*; do
   /system/bin/sh $FILE &
done

mount -o remount,ro /system

echo "...init.d finished."
